[package]
name = "mkvmon"
version = "0.3.1"
edition = "2024"

[dependencies]
chrono = "0.4.40"
notify = "8.0.0"
serde = { version = "1.0.218", features = [ "derive" ] }
serde_json = "1.0.140"
signal-hook = "0.3.17"
