# .github/workflows/build.yml
name: Create and publish a binary

on:
  push:
    branches: [master]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Rust Release Binary
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: release
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
